import type { Metadata } from 'next';

import { Geist, Geist_Mono } from 'next/font/google';

import RootLayoutClient from './client';
import './globals.css';

const geistSans = Geist({
	variable: '--geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<RootLayoutClient>{children}</RootLayoutClient>
			</body>
		</html>
	);
}
